### ISSUE TITLE
Debug Build by Default

### ISSUE THREAD

**Issue by jamespack** [the-bobo/easychromium#1]
Is there a reason that you are building debug version by default?

**Comment by the-bobo** [comment]
hi @jamespack - i was confused when first building the script, please see https://groups.google.com/a/chromium.org/d/msg/chromium-dev/a-UHhvZ2SP0/7WQwP-fTAgAJ for planned upgrades to come soon (maybe this weekend if i have time)

**Comment by jamespack** [comment]
That would be an easy one ;). The script worked well by the way. Very nice!

Sent from Outlook Mobile

On Tue, Jan 19, 2016 at 1:15 PM -0800, "Bobo" notifications@github.com wrote:

hi @jamespack - i was confused when first building the script, please see https://groups.google.com/a/chromium.org/d/msg/chromium-dev/a-UHhvZ2SP0/7WQwP-fTAgAJ for planned upgrades to come soon (maybe this weekend if i have time)

**Comment by the-bobo** [comment]
thanks :)
